const usersData = [
  {
    email: 'CarolC',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Caroline Goularte',
      creci: '77802',
      contato: '(53)981134581',
      about: 'Nos últimos 6 meses, você tem uma média de 11,6 Ages e 4,8 Placas P. por mês.',
      photo: '/fotosPerfis/CarolC.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/checksf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/checksf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'ClaudioUP',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Cláudio Gonçalves',
      creci: '43343',
      contato: '53991846449',
      about: 'Nos últimos 6 meses, você tem uma média de 9,5 Ages e 5,8 Placas P. por mês.',
      photo: '/fotosPerfis/ClaudioUP.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/checksf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/checksf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'GabrielM',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Gabriel Martini',
      creci: '62286',
      contato: '53981621706',
      about: 'Nos últimos 5 meses, você tem uma média de 9 Ages e 2,6 Placas P. por mês.',
      photo: '/fotosPerfis/GabrielM.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/retsf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/xsf.png',
        maio: '/xsf.png',
        junho: '/xsf.png',
        julho: '/xsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'Illie',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Illie Corrêa',
      creci: '63904',
      contato: '53991892028',
      about: 'Nos últimos 6 meses, você tem uma média de 4,6 Ages e 2,1 Placas P. por mês.',
      photo: '/fotosPerfis/Illie.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/xsf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/xsf.png',
        maio: '/xsf.png',
        junho: '/xsf.png',
        julho: '/xsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'MarcioM',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Marcio Maciel',
      creci: '52782',
      contato: '53991892028',
      about: 'Nos últimos 4 meses, você tem uma média de 6,5 Ages e 0,5 Placas P. por mês.',
      photo: '/fotosPerfis/MarcioM.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/retsf.png',
        fevereiro: '/retsf.png',
        marco: '/xsf.png',
        abril: '/xsf.png',
        maio: '/xsf.png',
        junho: '/xsf.png',
        julho: '/checksf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'NetoS',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Neto Schmidt',
      creci: '54222',
      contato: '53981398861',
      about: 'Nos últimos 6 meses, você tem uma média de 10,5 Ages e 5,3 Placas P. por mês.',
      photo: '/fotosPerfis/NetoS.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/xsf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/xsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'RafaelA',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Rafael Andrada',
      creci: '67694',
      contato: '53999477271',
      about: 'Nos últimos 4 meses, você tem uma média de 7,25 Ages e 0,25 Placas P. por mês.',
      photo: '/fotosPerfis/RafaelA.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/retsf.png',
        fevereiro: '/retsf.png',
        marco: '/xsf.png',
        abril: '/xsf.png',
        maio: '/xsf.png',
        junho: '/xsf.png',
        julho: '/xsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'TheodoroC',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Theodoro Ceron',
      creci: '71570',
      contato: '53981104541',
      about: 'Nos últimos 5 meses, você tem uma média de 5,2 Ages e 0,8 Placas P. por mês.',
      photo: '/fotosPerfis/TheodoroC.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/retsf.png',
        fevereiro: '/xsf.png',
        marco: '/xsf.png',
        abril: '/xsf.png',
        maio: '/xsf.png',
        junho: '/xsf.png',
        julho: '/checksf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'AnaBia',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Ana Bia Mattos',
      creci: '69645',
      contato: '53984099406',
      about: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
      photo: '/fotosPerfis/AnaBia.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/retsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'DanmersomS',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Danmersom Souza',
      creci: '00',
      contato: '53984373036',
      about: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
      photo: '/fotosPerfis/DanmersomS.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/retsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },  
  {
    email: 'JacquesD',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Jacques Douglas',
      creci: '61583',
      contato: '53984651668',
      about: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
      photo: '/fotosPerfis/JacquesD.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/retsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'JordanaC',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Jordana Coutinho',
      creci: '58083',
      contato: '53999977072',
      about: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
      photo: '/fotosPerfis/JordanaC.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/retsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'RafaelP',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Rafael Paiva',
      creci: '41773',
      contato: '53984477467',
      about: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
      photo: '/fotosPerfis/RafaelP.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/retsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  {
    email: 'RossanaP',
    password: 'vivamudanca',
    role: 'home',
    profile: {
      name: 'Rossana Pail',
      creci: '00',
      contato: '53984121080',
      about: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
      photo: '/fotosPerfis/RossanaP.jpg', // Caminho relativo à pasta pública
      agenciamentos: {
        janeiro: '/checksf.png',
        fevereiro: '/checksf.png',
        marco: '/xsf.png',
        abril: '/checksf.png',
        maio: '/xsf.png',
        junho: '/checksf.png',
        julho: '/retsf.png',
        agosto: '/retsf.png',
        setembro: '/retsf.png',
        outubro: '/retsf.png',
        novembro: '/retsf.png',
        dezembro: '/retsf.png',
      },
    },
  },
  // Adicione outros usuários com o mesmo formato
];

export default usersData;
